@startuml Social_Network_ER

package "Сущности социальной сети" {
    entity "Пользователь" as User {
        * user_id : int <<generated>>
        --
        * username : varchar(255)
        * password_md5 : varchar(64)
    }
    entity "Стена с постами" as Wall {
        * wall_id : int <<generated>>
        --
        * user_id : int <<FK>>
    }
    entity "Пост" as Post {
        * post_id : int <<generated>>
        --
        * content : text
        * created_at : datetime
        * wall_id : int <<FK>>
    }
    entity "Комментарий" as Comment {
        * comment_id : int <<generated>>
        --
        * content : text
        * created_at : datetime
        * post_id : int <<FK>>
        * user_id : int <<FK>>
        * comment_level: int
        prev_comment_id: int <<FK>>
    }
    entity "Статистика" as Statistics {
        * statistics_id : int <<generated>>
        --
        * likes : int
        * views : int
        * post_id : int <<FK>>
    }
}

User ||--o| Wall
Wall ||--o{ Post
Post ||--o{ Comment
Post ||--|| Statistics
@enduml