@startuml Social_Network_ER

package "Сущности социальной сети" {
    entity "Пользователь" as User {
        * login : varchar
        --
        * password_hash : varchar
        first_name : varchar
        last_name : varchar
        birth_date : date
        email : varchar
        phone : varchar
        token : varchar
    }
    entity "Пост" as Post {
        * post_id : int <<generated>>
        --
        * content : varchar
        * created_at : datetime
        * login : varchar <<FK>>
    }
    entity "Комментарий" as Comment {
        * comment_id : int <<generated>>
        --
        * content : varchar
        * created_at : datetime
        * post_id : int <<FK>>
        * login : varchar <<FK>>
        * comment_level: int
        prev_comment_id: int <<FK>>
    }
    entity "Статистика" as Statistics {
        * statistics_id : int <<generated>>
        --
        * likes : int
        * views : int
        * post_id : int <<FK>>
    }
}

User --o{ Post
Post --o{ Comment
Post --|| Statistics
Comment |o-- Comment
Comment --|| User
@enduml