// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: protos/posts.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServicePostsClient is the client API for ServicePosts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServicePostsClient interface {
	Func(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Int, error)
}

type servicePostsClient struct {
	cc grpc.ClientConnInterface
}

func NewServicePostsClient(cc grpc.ClientConnInterface) ServicePostsClient {
	return &servicePostsClient{cc}
}

func (c *servicePostsClient) Func(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Int, error) {
	out := new(Int)
	err := c.cc.Invoke(ctx, "/service_posts.ServicePosts/Func", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServicePostsServer is the server API for ServicePosts service.
// All implementations must embed UnimplementedServicePostsServer
// for forward compatibility
type ServicePostsServer interface {
	Func(context.Context, *Empty) (*Int, error)
	mustEmbedUnimplementedServicePostsServer()
}

// UnimplementedServicePostsServer must be embedded to have forward compatible implementations.
type UnimplementedServicePostsServer struct {
}

func (UnimplementedServicePostsServer) Func(context.Context, *Empty) (*Int, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Func not implemented")
}
func (UnimplementedServicePostsServer) mustEmbedUnimplementedServicePostsServer() {}

// UnsafeServicePostsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServicePostsServer will
// result in compilation errors.
type UnsafeServicePostsServer interface {
	mustEmbedUnimplementedServicePostsServer()
}

func RegisterServicePostsServer(s grpc.ServiceRegistrar, srv ServicePostsServer) {
	s.RegisterService(&ServicePosts_ServiceDesc, srv)
}

func _ServicePosts_Func_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicePostsServer).Func(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service_posts.ServicePosts/Func",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicePostsServer).Func(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ServicePosts_ServiceDesc is the grpc.ServiceDesc for ServicePosts service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServicePosts_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service_posts.ServicePosts",
	HandlerType: (*ServicePostsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Func",
			Handler:    _ServicePosts_Func_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/posts.proto",
}
