# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stats.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstats.proto\x12\rservice_stats\x1a\x1bgoogle/protobuf/empty.proto\"\x17\n\x06PostId\x12\r\n\x05value\x18\x01 \x01(\x04\"6\n\x08\x43\x61tegory\x12*\n\x05value\x18\x01 \x01(\x0e\x32\x1b.service_stats.StatCategory\")\n\tPostStats\x12\r\n\x05views\x18\x01 \x01(\x04\x12\r\n\x05likes\x18\x02 \x01(\x04\"3\n\x07TopPost\x12\n\n\x02id\x18\x01 \x01(\x04\x12\r\n\x05login\x18\x02 \x01(\t\x12\r\n\x05\x63ount\x18\x03 \x01(\x04\"1\n\x08TopPosts\x12%\n\x05posts\x18\x01 \x03(\x0b\x32\x16.service_stats.TopPost\"\'\n\x07TopUser\x12\r\n\x05login\x18\x01 \x01(\t\x12\r\n\x05likes\x18\x02 \x01(\x04\"1\n\x08TopUsers\x12%\n\x05users\x18\x01 \x03(\x0b\x32\x16.service_stats.TopUser*$\n\x0cStatCategory\x12\t\n\x05VIEWS\x10\x00\x12\t\n\x05LIKES\x10\x01\x32\xd6\x01\n\x0cServiceStats\x12\x41\n\x0eget_post_stats\x12\x15.service_stats.PostId\x1a\x18.service_stats.PostStats\x12\x41\n\rget_top_posts\x12\x17.service_stats.Category\x1a\x17.service_stats.TopPosts\x12@\n\rget_top_users\x12\x16.google.protobuf.Empty\x1a\x17.service_stats.TopUsersb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATCATEGORY']._serialized_start=379
  _globals['_STATCATEGORY']._serialized_end=415
  _globals['_POSTID']._serialized_start=59
  _globals['_POSTID']._serialized_end=82
  _globals['_CATEGORY']._serialized_start=84
  _globals['_CATEGORY']._serialized_end=138
  _globals['_POSTSTATS']._serialized_start=140
  _globals['_POSTSTATS']._serialized_end=181
  _globals['_TOPPOST']._serialized_start=183
  _globals['_TOPPOST']._serialized_end=234
  _globals['_TOPPOSTS']._serialized_start=236
  _globals['_TOPPOSTS']._serialized_end=285
  _globals['_TOPUSER']._serialized_start=287
  _globals['_TOPUSER']._serialized_end=326
  _globals['_TOPUSERS']._serialized_start=328
  _globals['_TOPUSERS']._serialized_end=377
  _globals['_SERVICESTATS']._serialized_start=418
  _globals['_SERVICESTATS']._serialized_end=632
# @@protoc_insertion_point(module_scope)
