name: Stats service, service tests

on:
  push:
    paths:
      - 'stats/**'
  pull_request:
    paths:
      - 'stats/**'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: stats/
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-test.txt
      - name: Run tests
        run: python -m unittest service_tests.py -v
